
const sizeMacros = Object.fromEntries([
  "Huge", "huge", "LARGE", "Large", "large", "normalsize",
  "small", "footnotesize", "scriptsize", "tiny"
].map((size) => [size, (a) => `{\\${size} ${a}}`]));

const delimiterSizeMacros = Object.fromEntries([
  "left", "middle", "right",
  "big", "bigl", "bigm", "bigr",
  "Big", "Bigl", "Bigm", "Bigr",
  "bigg", "biggl", "biggm", "biggr",
  "Bigg", "Biggl", "Biggm", "Biggr",
].map((size) => [size, (a) => `\\${size} ${a}`]));

const ordinaryUnaryMacros = Object.fromEntries([
  "url", "cancel", "bcancel", "xcancel", "sout",
  "boxed", "phase", "tag", "tag*", "raisebox",
  "kern", "mkern", "mskip", "hskip", "hspace",
  "hspace*", "phantom", "hphantom", "vphantom", 
  "bra", "ket", "braket", "Bra", "Ket", "Braket", 
].map((name) => [name, (a) => `\\${name}{${a}}`]));

export const unary = {
  "sqrt": (a) => `√${a}`,
  "not": (a) => "\u0338" + `${a}`,
  ...ordinaryUnaryMacros,

  /* font size */
  ...sizeMacros,
  ...delimiterSizeMacros,

  /* font styles */
  "mathrm": (a) => `\\mathrm{${a}}`,
  "mathnormal": (a) => `\\mathnormal{${a}}`,
  "textrm": (a) => `\\textrm{${a}}`,
  "rm": (a) => `{\\rm{${a}}}`,
  "textnormal": (a) => `\\textnormal{${a}}`,
  "text": (a) => `\\text{${a}}`,
  "textup": (a) => `\\textup{${a}}`,
  "mathit": (a) => `\\mathit{${a}}`,
  "textit": (a) => `\\textit{${a}}`,
  "it": (a) => `{\\it{${a}}}`,
  "emph": (a) => `\\emph{${a}}`,
  "mathbf": (a) => `\\mathbf{${a}}`,
  "textbf": (a) => `\\textbf{${a}}`,
  "bf": (a) => `{\\bf{${a}}}`,
  "bold": (a) => `\\bold{${a}}`,
  "boldsymbol": (a) => `\\boldsymbol{${a}}`,
  "bm": (a) => `\\bm{${a}}`,
  "textmd": (a) => `\\textmd{${a}}`,
  "mathtt": (a) => `\\mathtt{${a}}`,
  "texttt": (a) => `\\texttt{${a}}`,
  "tt": (a) => `{\\tt{${a}}}`,
  "mathsf": (a) => `\\mathsf{${a}}`,
  "textsf": (a) => `\\textsf{${a}}`,
  "sf": (a) => `{\\sf{${a}}}`,
  "mathsfit": (a) => `\\mathsfit{${a}}`,
  "Bbb": (a) => `\\Bbb{${a}}`,
  "mathbb": (a) => `\\mathbb{${a}}`,
  "frak": (a) => `\\frak{${a}}`,
  "mathfrak": (a) => `\\mathfrak{${a}}`,
  "mathcal": (a) => `\\mathcal{${a}}`,
  "cal": (a) => `\\cal{${a}}`,
  "mathscr": (a) => `\\mathscr{${a}}`,

  /* accents */
  "acute": (a) => "\u0301" + `${a}`,
  "bar": (a) => "\u0304" + `${a}`,
  "breve": (a) => "\u0306" + `${a}`,
  "check": (a) => `\\check{${a}}`,
  "dot": (a) => "\u0307" + `${a}`,
  "ddot": (a) => "\u0308" + `${a}`,
  "dddot": (a) => `\\dddot{${a}}`,
  "ddddot": (a) => `\\ddddot{${a}}`,
  "grave": (a) => "\u0300" + `${a}`,
  "hat": (a) => "\u0302" + `${a}`,
  "tilde": (a) => "\u0303" + `${a}`,
  "mathring": (a) => `\\mathring{${a}}`,
  "widetilde": (a) => `\\widetilde{${a}}`,
  "overgroup": (a) => `\\overgroup{${a}}`,
  "utilde": (a) => `\\utilde{${a}}`,
  "vec": (a) => `\\vec{${a}}`,
  "Overrightarrow": (a) => `\\Overrightarrow{${a}}`,
  "overleftarrow": (a) => `\\overleftarrow{${a}}`,
  "overrightarrow": (a) => `\\overrightarrow{${a}}`,
  "underleftarrow": (a) => `\\underleftarrow{${a}}`,
  "underrightarrow": (a) => `\\underrightarrow{${a}}`,
  "overleftharpoon": (a) => `\\overleftharpoon{${a}}`,
  "overrightharpoon": (a) => `\\overrightharpoon{${a}}`,
  "overleftrightarrow": (a) => `\\overleftrightarrow{${a}}`,
  "underleftrightarrow": (a) => `\\underleftrightarrow{${a}}`,
  "overbrace": (a) => `\\overbrace{${a}}`,
  "underbrace": (a) => `\\underbrace{${a}}`,
  "overline": (a) => "\u0305" + `${a}`,
  "underline": (a) => `\\underline{${a}}`,
  "overlinesegment": (a) => `\\overlinesegment{${a}}`,
  "underlinesegment": (a) => `\\underlinesegment{${a}}`,
  "widecheck": (a) => `\\widecheck{${a}}`,
  "widehat": (a) => `\\widehat{${a}}`,
  "underbar": (a) => `\\underbar{${a}}`,
  "'": (a) => "\u0301" + `${a}`,
  "~": (a) => "\u0303" + `${a}`,
  ".": (a) => "\u0307" + `${a}`,
  "H": (a) => "\u030B" + `${a}`,
  "`": (a) => "\u0300" + `${a}`,
  "=": (a) => "\u0304" + `${a}`,
  '"': (a) => "\u0308" + `${a}`,
  "v": (a) => "\u030C" + `${a}`,
  "^": (a) => "\u0302" + `${a}`,
  "u": (a) => "\u0306" + `${a}`,
  "r": (a) => "\u030A" + `${a}`,
};
